# Generated by Django 5.2.9 on 2025-12-30 11:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название домена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание домена')),
            ],
            options={
                'verbose_name': 'Домен оценки',
                'verbose_name_plural': 'Домены оценки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('department_owner', models.CharField(max_length=255, verbose_name='Ответственное ведомство/владелец')),
                ('product_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на продукт')),
                ('launch_date', models.DateField(blank=True, null=True, verbose_name='Дата запуска')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
            ],
            options={
                'verbose_name': 'Цифровой продукт',
                'verbose_name_plural': 'Цифровые продукты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название критерия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание критерия')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)], verbose_name='Вес в домене (%)')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='core.domain', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Критерий оценки',
                'verbose_name_plural': 'Критерии оценки',
                'ordering': ['domain', 'name'],
                'unique_together': {('domain', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RatingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Балл')),
                ('description', models.TextField(verbose_name='Дескриптор балла')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_scales', to='core.criterion', verbose_name='Критерий')),
            ],
            options={
                'verbose_name': 'Шкала оценки',
                'verbose_name_plural': 'Шкалы оценки',
                'ordering': ['criterion', 'score'],
                'unique_together': {('criterion', 'score')},
            },
        ),
    ]
