# Generated by Django 5.2.9 on 2025-12-30 11:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицировано')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_criteria', to=settings.AUTH_USER_MODEL, verbose_name='Назначено')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.criterion', verbose_name='Критерий')),
            ],
            options={
                'verbose_name': 'Назначенный критерий',
                'verbose_name_plural': 'Назначенные критерии',
                'ordering': ['evaluation_session', 'criterion__name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_value', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Балл по шкале')),
                ('metric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Числовое значение метрики')),
                ('file_evidence', models.FileField(blank=True, null=True, upload_to='evaluation_evidence/', verbose_name='Файл-доказательство')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('assigned_criterion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='core.assignedcriterion', verbose_name='Назначенный критерий')),
            ],
            options={
                'verbose_name': 'Ответ на оценку',
                'verbose_name_plural': 'Ответы на оценку',
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('archived', 'В архиве')], default='pending', max_length=50, verbose_name='Статус')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Создана')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Оценочная сессия',
                'verbose_name_plural': 'Оценочные сессии',
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='assignedcriterion',
            name='evaluation_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_criteria', to='core.evaluationsession', verbose_name='Оценочная сессия'),
        ),
        migrations.AlterUniqueTogether(
            name='assignedcriterion',
            unique_together={('evaluation_session', 'criterion')},
        ),
    ]
