# Generated by Django 5.2.9 on 2025-12-30 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assignedcriterion_evaluationanswer_evaluationsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)], verbose_name='Вес в индексе зрелости (%)'),
        ),
    ]
