# Generated by Django 5.2.9 on 2026-04-25 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_role_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationanswer',
            name='metric_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Числовое значение метрики'),
        ),
    ]
