# Generated by Django 5.2.9 on 2026-04-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_evaluationanswer_metric_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_avatars/', verbose_name='Фото профиля'),
        ),
    ]
